name: Secret Detection

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  detect-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'  # Specify your preferred Python version

      - name: Install detect-secrets
        run: |
          pip install detect-secrets

      - name: Run detect-secrets
        run: |
          detect-secrets scan > secrets_report.txt || echo "Secret detection failed"

      - name: List files
        run: ls -la

      - name: Upload secrets report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: secrets-detection-results
          path: secrets_report.txt
