name: Detect Secrets Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-detect-secrets:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repo
      - name: Checkout the repository
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Install dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gitpython
          pip install detect-secrets

      # Step 4: Run the detect-secrets scan
      - name: Run detect-secrets scan
        run: |
          python detect_secrets_scan.py

      # Step 5: Upload the detect-secrets result as an artifact
      - name: Upload detect-secrets result
        uses: actions/upload-artifact@v3
        with:
          name: detect-secrets-result
          path: '*.txt'
