name: Daily Trivy SCA Scan

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  trivy-sca-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Trivy
        run: |
          sudo apt-get update -y
          sudo apt-get install -y wget
          wget -qO- https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update -y
          sudo apt-get install -y trivy

      - name: Run Trivy SCA scan
        run: |
          trivy fs --scanners vuln --severity HIGH,CRITICAL,MEDIUM,LOW --ignore-unfixed --format table . > trivy_report.txt || echo "Trivy scan failed"

      - name: List files
        run: ls -la

      - name: Read Trivy report
        id: read_report
        run: echo "::set-output name=report::$(cat trivy_report.txt)"

      - name: Send email with Trivy results
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: Trivy SCA Scan Results - ${{ github.repository }}
          body: |
            Hello,

            Here are the results of the latest Trivy SCA scan for the repository ${{ github.repository }}:

            ${{ steps.read_report.outputs.report }}

            Best regards,
            GitHub Actions Bot
          to: "prince.lucideus@gmail.com"
          from: "princeraj.hnt@gmail.com"
